import type { RegistryBoard, BoardTemplate, ImportSource } from '@/types';

export const registryBoards: RegistryBoard[] = [
  // ==================== AVR (avr8js - MIT) ====================
  {
    id: 'arduino-uno',
    package: '@tscircuit/arduino-uno',
    name: 'Arduino Uno',
    description: 'The classic ATmega328P-based development board. Perfect for beginners and most projects.',
    author: 'Arduino/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'arduino-shield',
    dimensions: { width: '68.6mm', height: '53.4mm' },
    pinCount: { digital: 14, analog: 6, pwm: 6, i2c: 2, spi: 4, uart: 2 },
    voltage: 5,
    mcu: 'ATmega328P',
    architecture: 'avr',
    installed: true,
    tags: ['arduino', 'avr', 'beginner', '5v', 'classic', 'avr8js'],
    compatibleTemplates: ['blink', 'traffic-light', 'button-led', 'potentiometer-led', 'buzzer-melody', 'photoresistor', 'seven-segment'],
    tsciCommand: 'tsci add @tscircuit/arduino-uno',
    thumbnailColor: '#0078D7',
    emulator: 'avr8js',
  },
  {
    id: 'arduino-nano',
    package: '@tscircuit/arduino-nano',
    name: 'Arduino Nano',
    description: 'Compact breadboard-friendly ATmega328P board. Perfect for permanent projects.',
    author: 'Arduino/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '45mm', height: '18mm' },
    pinCount: { digital: 14, analog: 8, pwm: 6, i2c: 2, spi: 4, uart: 2 },
    voltage: 5,
    mcu: 'ATmega328P',
    architecture: 'avr',
    installed: true,
    tags: ['arduino', 'nano', 'breadboard', 'compact', 'avr8js'],
    compatibleTemplates: ['blink', 'button-led', 'potentiometer-led'],
    tsciCommand: 'tsci add @tscircuit/arduino-nano',
    thumbnailColor: '#00838F',
    emulator: 'avr8js',
  },
  {
    id: 'arduino-mega',
    package: '@tscircuit/arduino-mega',
    name: 'Arduino Mega 2560',
    description: 'High pin-count ATmega2560 board. Ideal for 3D printers, CNC, and complex projects.',
    author: 'Arduino/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'arduino-shield',
    dimensions: { width: '101.5mm', height: '53.4mm' },
    pinCount: { digital: 54, analog: 16, pwm: 15, i2c: 2, spi: 4, uart: 4 },
    voltage: 5,
    mcu: 'ATmega2560',
    architecture: 'avr',
    installed: false,
    tags: ['arduino', 'mega', '3d-printer', 'cnc', 'high-pin-count', 'avr8js'],
    compatibleTemplates: ['traffic-light', 'rgb-led', 'servo-control'],
    tsciCommand: 'tsci add @tscircuit/arduino-mega',
    thumbnailColor: '#1565C0',
    emulator: 'avr8js',
  },
  {
    id: 'attiny85',
    package: '@tscircuit/attiny85-digispark',
    name: 'ATtiny85 Digispark',
    description: 'Ultra-compact ATtiny85 board that fits in a USB port. Great for tiny projects.',
    author: 'Digistump/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '24mm', height: '12mm' },
    pinCount: { digital: 6, analog: 3, pwm: 2, i2c: 0, spi: 0, uart: 0 },
    voltage: 5,
    mcu: 'ATtiny85',
    architecture: 'avr',
    installed: false,
    tags: ['attiny', 'tiny', 'usb', 'digispark', 'compact', 'avr8js'],
    compatibleTemplates: ['blink', 'buzzer-melody'],
    tsciCommand: 'tsci add @tscircuit/attiny85-digispark',
    thumbnailColor: '#00695C',
    emulator: 'avr8js',
  },

  // ==================== RP2040 (rp2040js - MIT) ====================
  {
    id: 'raspberry-pi-pico',
    package: '@tscircuit/raspberry-pi-pico',
    name: 'Raspberry Pi Pico',
    description: 'RP2040 dual-core ARM Cortex-M0+ with programmable I/O (PIO). Runs MicroPython & C.',
    author: 'Raspberry Pi/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '51mm', height: '21mm' },
    pinCount: { digital: 26, analog: 4, pwm: 16, i2c: 2, spi: 2, uart: 2 },
    voltage: 3.3,
    mcu: 'RP2040',
    architecture: 'arm-cortex-m0',
    installed: false,
    tags: ['pico', 'rp2040', 'arm', 'pio', 'micropython', 'circuitpython', 'rp2040js'],
    compatibleTemplates: ['blink', 'traffic-light', 'servo-control'],
    tsciCommand: 'tsci add @tscircuit/raspberry-pi-pico',
    thumbnailColor: '#2E7D32',
    emulator: 'rp2040js',
  },
  {
    id: 'raspberry-pi-pico-w',
    package: '@tscircuit/raspberry-pi-pico-w',
    name: 'Raspberry Pi Pico W',
    description: 'RP2040 with onboard Infineon CYW43439 WiFi + BLE. IoT-ready Pico.',
    author: 'Raspberry Pi/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '51mm', height: '21mm' },
    pinCount: { digital: 26, analog: 4, pwm: 16, i2c: 2, spi: 2, uart: 2 },
    voltage: 3.3,
    mcu: 'RP2040',
    architecture: 'arm-cortex-m0',
    installed: false,
    tags: ['pico', 'pico-w', 'wifi', 'iot', 'rp2040', 'rp2040js'],
    tsciCommand: 'tsci add @tscircuit/raspberry-pi-pico-w',
    thumbnailColor: '#1B5E20',
    emulator: 'rp2040js',
  },

  // ==================== RISC-V (rvemu - MIT) ====================
  {
    id: 'esp32-c3-devkit',
    package: '@tscircuit/esp32-c3-devkit-m1',
    name: 'ESP32-C3-DevKitM-1',
    description: 'RISC-V single-core MCU with WiFi 4 and BLE 5.0. Server-side simulation via rvemu WASM.',
    author: 'Espressif/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '25mm', height: '52mm' },
    pinCount: { digital: 22, analog: 5, pwm: 6, i2c: 2, spi: 2, uart: 2 },
    voltage: 3.3,
    mcu: 'ESP32-C3',
    architecture: 'risc-v',
    installed: false,
    tags: ['esp32', 'esp32-c3', 'risc-v', 'wifi', 'ble', 'iot', 'rvemu', 'libriscv'],
    compatibleTemplates: ['blink', 'rgb-led'],
    tsciCommand: 'tsci add @tscircuit/esp32-c3-devkit-m1',
    thumbnailColor: '#E65100',
    emulator: 'riscv',
  },
  {
    id: 'risc-v-feather',
    package: '@tscircuit/risc-v-feather',
    name: 'RISC-V Feather',
    description: 'Adafruit Feather form factor with RISC-V processor. Open-source ISA, IoT-ready.',
    author: 'Adafruit/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'feather',
    dimensions: { width: '50.8mm', height: '22.9mm' },
    pinCount: { digital: 21, analog: 7, pwm: 8, i2c: 2, spi: 2, uart: 2 },
    voltage: 3.3,
    architecture: 'risc-v',
    installed: false,
    tags: ['risc-v', 'feather', 'adafruit', 'open-source', 'rvemu'],
    tsciCommand: 'tsci add @tscircuit/risc-v-feather',
    thumbnailColor: '#827717',
    emulator: 'riscv',
  },

  // ==================== Xtensa/ESP32 (Espruino - MIT/MPL) ====================
  {
    id: 'esp32-devkit',
    package: '@tscircuit/esp32-devkit-v1',
    name: 'ESP32 DevKit V1',
    description: 'WiFi + BLE dual-core Xtensa processor. IoT powerhouse. Espruino Emscripten simulation.',
    author: 'Espressif/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '55mm', height: '28mm' },
    pinCount: { digital: 34, analog: 18, pwm: 16, i2c: 2, spi: 4, uart: 2 },
    voltage: 3.3,
    mcu: 'ESP32-WROOM-32',
    architecture: 'xtensa',
    installed: false,
    tags: ['esp32', 'wifi', 'bluetooth', 'iot', 'dual-core', 'espruino', 'server-sim'],
    compatibleTemplates: ['blink', 'rgb-led'],
    tsciCommand: 'tsci add @tscircuit/esp32-devkit-v1',
    thumbnailColor: '#E65100',
    emulator: 'espruino',
  },
  {
    id: 'esp8266-nodemcu',
    package: '@tscircuit/esp8266-nodemcu',
    name: 'ESP8266 NodeMCU',
    description: 'Affordable WiFi board based on ESP8266. Great entry point for IoT projects.',
    author: 'Espressif/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '58mm', height: '31mm' },
    pinCount: { digital: 17, analog: 1, pwm: 10, i2c: 2, spi: 2, uart: 2 },
    voltage: 3.3,
    mcu: 'ESP8266',
    architecture: 'xtensa',
    installed: false,
    tags: ['esp8266', 'wifi', 'iot', 'nodemcu', 'affordable', 'espruino'],
    tsciCommand: 'tsci add @tscircuit/esp8266-nodemcu',
    thumbnailColor: '#BF360C',
    emulator: 'espruino',
  },

  // ==================== ARM Cortex-M (M-ulator - MIT) ====================
  {
    id: 'stm32-nucleo-f411re',
    package: '@tscircuit/stm32-nucleo-f411re',
    name: 'STM32 Nucleo-F411RE',
    description: 'ARM Cortex-M4F at 100MHz with Arduino headers. Advanced prototyping board.',
    author: 'STMicroelectronics/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'stm32-nucleo',
    dimensions: { width: '70mm', height: '75mm' },
    pinCount: { digital: 50, analog: 16, pwm: 12, i2c: 3, spi: 4, uart: 6 },
    voltage: 3.3,
    mcu: 'STM32F411RE',
    architecture: 'arm-cortex-m4',
    installed: false,
    tags: ['stm32', 'arm', 'cortex-m4', 'nucleo', 'advanced', 'm-ulator'],
    tsciCommand: 'tsci add @tscircuit/stm32-nucleo-f411re',
    thumbnailColor: '#4527A0',
    emulator: 'rp2040js',
  },
  {
    id: 'stm32-nucleo-f103rb',
    package: '@tscircuit/stm32-nucleo-f103rb',
    name: 'STM32 Nucleo-F103RB',
    description: 'ARM Cortex-M3 "Blue Pill" compatible. Classic STM32 development platform.',
    author: 'STMicroelectronics/tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'microcontroller',
    formFactor: 'stm32-nucleo',
    dimensions: { width: '70mm', height: '75mm' },
    pinCount: { digital: 37, analog: 10, pwm: 12, i2c: 3, spi: 3, uart: 3 },
    voltage: 3.3,
    mcu: 'STM32F103RB',
    architecture: 'arm-cortex-m3',
    installed: false,
    tags: ['stm32', 'arm', 'cortex-m3', 'blue-pill', 'm-ulator'],
    tsciCommand: 'tsci add @tscircuit/stm32-nucleo-f103rb',
    thumbnailColor: '#311B92',
    emulator: 'rp2040js',
  },

  // ==================== SHIELDS & HATS ====================
  {
    id: 'arduino-ethernet-shield',
    package: '@tscircuit/arduino-ethernet-shield',
    name: 'Ethernet Shield',
    description: 'Arduino shield with W5500 Ethernet chip. Adds wired networking.',
    author: 'tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'shield',
    formFactor: 'arduino-shield',
    dimensions: { width: '68.6mm', height: '53.4mm' },
    pinCount: { digital: 10, analog: 0, pwm: 0, i2c: 0, spi: 4, uart: 0 },
    voltage: 5,
    installed: false,
    tags: ['ethernet', 'network', 'w5500', 'iot', 'shield'],
    tsciCommand: 'tsci add @tscircuit/arduino-ethernet-shield',
    thumbnailColor: '#283593',
    emulator: 'avr8js',
  },
  {
    id: 'arduino-motor-shield',
    package: '@tscircuit/arduino-motor-shield',
    name: 'Motor Shield',
    description: 'Dual H-bridge motor driver. Drive 2 DC motors or 1 stepper motor.',
    author: 'tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'shield',
    formFactor: 'arduino-shield',
    dimensions: { width: '68.6mm', height: '53.4mm' },
    pinCount: { digital: 8, analog: 0, pwm: 4, i2c: 0, spi: 0, uart: 0 },
    voltage: 5,
    installed: false,
    tags: ['motor', 'h-bridge', 'stepper', 'robot', 'shield'],
    tsciCommand: 'tsci add @tscircuit/arduino-motor-shield',
    thumbnailColor: '#C62828',
    emulator: 'avr8js',
  },

  // ==================== BREAKOUT / MODULES ====================
  {
    id: 'ssd1306-oled',
    package: '@tscircuit/ssd1306-oled-breakout',
    name: 'SSD1306 OLED 128x64',
    description: 'I2C OLED display breakout. Perfect for status displays and small UIs.',
    author: 'tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'display-module',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '27mm', height: '28mm' },
    pinCount: { digital: 4, analog: 0, pwm: 0, i2c: 2, spi: 0, uart: 0 },
    voltage: 3.3,
    installed: false,
    tags: ['oled', 'display', 'i2c', 'ssd1306', '128x64'],
    tsciCommand: 'tsci add @tscircuit/ssd1306-oled-breakout',
    thumbnailColor: '#1A237E',
    emulator: 'avr8js',
  },
  {
    id: 'dht22-sensor',
    package: '@tscircuit/dht22-sensor-module',
    name: 'DHT22 Temp & Humidity',
    description: 'Digital temperature and humidity sensor. Accurate to +/-0.5C.',
    author: 'tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'sensor-module',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '15mm', height: '25mm' },
    pinCount: { digital: 3, analog: 0, pwm: 0, i2c: 0, spi: 0, uart: 0 },
    voltage: 3.3,
    installed: false,
    tags: ['temperature', 'humidity', 'sensor', 'dht22', 'weather'],
    tsciCommand: 'tsci add @tscircuit/dht22-sensor-module',
    thumbnailColor: '#4E342E',
    emulator: 'avr8js',
  },
  {
    id: 'hx711-load-cell',
    package: '@tscircuit/hx711-load-cell-amp',
    name: 'HX711 Load Cell Amplifier',
    description: '24-bit ADC for load cells and strain gauges. Build your own scales.',
    author: 'tscircuit',
    version: '1.0.0',
    license: 'MIT',
    category: 'breakout',
    formFactor: 'breadboard-friendly',
    dimensions: { width: '20mm', height: '20mm' },
    pinCount: { digital: 4, analog: 2, pwm: 0, i2c: 0, spi: 0, uart: 0 },
    voltage: 5,
    installed: false,
    tags: ['hx711', 'load-cell', 'scale', 'adc', 'weight'],
    tsciCommand: 'tsci add @tscircuit/hx711-load-cell-amp',
    thumbnailColor: '#37474F',
    emulator: 'avr8js',
  },
];

export const boardTemplates: BoardTemplate[] = [
  {
    id: 'arduino-shield',
    name: 'Arduino Shield',
    description: 'Standard Arduino R3 shield with headers, mounting holes, and ICSP connector',
    baseWidth: '68.6mm',
    baseHeight: '53.4mm',
    defaultMountingHoles: true,
    defaultHeaders: true,
    defaultUsbConnector: false,
    defaultPowerIndicator: true,
  },
  {
    id: 'rpi-hat',
    name: 'Raspberry Pi HAT',
    description: 'Raspberry Pi HAT with 40-pin header, EEPROM ID, and standard mounting',
    baseWidth: '65mm',
    baseHeight: '56.5mm',
    defaultMountingHoles: true,
    defaultHeaders: true,
    defaultUsbConnector: false,
    defaultPowerIndicator: true,
  },
  {
    id: 'custom',
    name: 'Custom Board',
    description: 'Fully custom board with configurable dimensions, connectors, and mounting',
    baseWidth: '50mm',
    baseHeight: '30mm',
    defaultMountingHoles: false,
    defaultHeaders: false,
    defaultUsbConnector: false,
    defaultPowerIndicator: false,
  },
  {
    id: 'feather',
    name: 'Adafruit Feather',
    description: 'Feather form factor with LiPo charging, USB-C, and STEMMA QT connector',
    baseWidth: '50.8mm',
    baseHeight: '22.9mm',
    defaultMountingHoles: true,
    defaultHeaders: true,
    defaultUsbConnector: true,
    defaultPowerIndicator: true,
  },
  {
    id: 'qwiic',
    name: 'SparkFun Qwiic',
    description: 'Qwiic/I2C breakout with standard connector for rapid prototyping',
    baseWidth: '25.4mm',
    baseHeight: '15.2mm',
    defaultMountingHoles: false,
    defaultHeaders: false,
    defaultUsbConnector: false,
    defaultPowerIndicator: false,
  },
  {
    id: 'stm32-nucleo',
    name: 'STM32 Nucleo',
    description: 'ST Nucleo-64 form factor with Arduino headers and Morpho connectors',
    baseWidth: '70mm',
    baseHeight: '75mm',
    defaultMountingHoles: true,
    defaultHeaders: true,
    defaultUsbConnector: true,
    defaultPowerIndicator: true,
  },
];

export const importSources: ImportSource[] = [
  {
    type: 'tscircuit-registry',
    name: 'tscircuit Registry',
    description: 'Search and install boards/components from the official tscircuit registry using tsci CLI',
    formats: ['tscircuit', 'circuit-json'],
    icon: 'Package',
  },
  {
    type: 'jlcpcb',
    name: 'JLCPCB Component Library',
    description: 'Import from 500K+ components with footprints, 3D models, and schematics',
    formats: ['jlcpcb-id', 'csv'],
    icon: 'Database',
  },
  {
    type: 'kicad',
    name: 'KiCad Project Import',
    description: 'Import KiCad footprints, schematic symbols, and board layouts',
    formats: ['.kicad_mod', '.kicad_sym', '.kicad_pcb'],
    icon: 'FileCode',
  },
  {
    type: 'snapeda',
    name: 'SnapEDA',
    description: 'Import verified component footprints and symbols from SnapEDA',
    formats: ['.brd', '.sch'],
    icon: 'Search',
  },
  {
    type: 'custom',
    name: 'Custom Import',
    description: 'Import custom board definitions from JSON or CSV files',
    formats: ['.json', '.csv'],
    icon: 'Upload',
  },
];

export function getBoardById(id: string): RegistryBoard | undefined {
  return registryBoards.find((b) => b.id === id);
}

export function getInstalledBoards(): RegistryBoard[] {
  return registryBoards.filter((b) => b.installed);
}

export function searchBoards(query: string): RegistryBoard[] {
  const q = query.toLowerCase();
  return registryBoards.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.tags.some((t) => t.includes(q)) ||
      b.mcu?.toLowerCase().includes(q) ||
      b.architecture?.includes(q) ||
      b.category.includes(q)
  );
}

export function getBoardsByCategory(cat: RegistryBoard['category']): RegistryBoard[] {
  return registryBoards.filter((b) => b.category === cat);
}

export function getBoardsByArchitecture(arch: RegistryBoard['architecture']): RegistryBoard[] {
  return registryBoards.filter((b) => b.architecture === arch);
}

export function getBoardsByEmulator(emulator: string): RegistryBoard[] {
  return registryBoards.filter((b) => (b as any).emulator === emulator);
}
